#!/bin/bash
set -e

MAIL_DOMAIN=${MAIL_DOMAIN:-}
URL_HOST=${URL_HOST:-}
LANGUAGE=${LANGUAGE:-EN}
MM_PASSWORD=${MM_PASSWORD:-}
ADMIN_EMAIL=${ADMIN_EMAIL:-}

export MAIL_DOMAIN
export URL_HOST
export LANGUAGE
export MM_PASSWORD
export ADMIN_EMAIL

cp -f /etc/mailman/mm_cfg.py.tpl /etc/mailman/mm_cfg.py
cp -f /etc/exim4/update-exim4.conf.conf.tpl /etc/exim4/update-exim4.conf.conf
# Substitute configuration
for VARIABLE in `env | cut -f1 -d=`; do
  sed -i "s={{ $VARIABLE }}=${!VARIABLE}=g" /etc/mailman/mm_cfg.py
  sed -i "s={{ $VARIABLE }}=${!VARIABLE}=g" /etc/exim4/update-exim4.conf.conf
done

if [ ! -d /var/lib/mailman/lists ] 
then
  rsync -a --progress /mailman/ /var/lib/mailman/
fi

NB_LISTS=$(ls /var/lib/mailman/lists | wc -l)
if [ $NB_LISTS -eq 0 ]
then 
  newlist --quiet mailman $ADMIN_EMAIL $MM_PASSWORD
fi

/etc/init.d/exim4 start
/etc/init.d/mailman start
/etc/init.d/apache2 start

tail -f /var/log/mailman/* /var/log/exim4/mainlog
